#!/bin/bash
# Convert various files to epub

set -o nounset
set -o errexit

if [[ $# == 0 ]]; then
	echo "missing args"
	exit -1
fi

INP="$1"

if [[ $# -gt 1 ]]; then
	CURDIR=$(pwd)
	OUT="$(basename "$CURDIR").epub"
else
	OUT="${INP%\.*}.epub"
fi

OPT=""
EXT=${INP##*\.}

echo "IN: $*"
echo "OUT: $OUT"

case "$EXT" in
	html|htm)
		#OPT='--breadth-first --level1-toc '//h:h1' --level2-toc '//h:h2' --level3-toc '//h:h3' --disable-format-scene-breaks'
		pandoc -t epub3 --smart --webtex --epub-chapter-level=1 -o "$OUT" "$@"
		;;
	*)
		# calibre for other
		shift
		OPT="$OPT "
		ebook-convert "$INP" "$OUT" -v \
			--no-default-epub-cover --language pl --epub-flatten --pretty-print \
			--remove-paragraph-spacing --smarten-punctuation --enable-heuristics \
			--extra-css "$HOME/books/my.css" \
			--disable-format-scene-breaks "$@"
		;;
esac


