#!/usr/bin/python
import sys
import os

args = ['/usr/bin/iceweasel']
for arg in sys.argv[1:]:
    if arg.startswith('openURL('):
        arg = arg[8:-1]
    args.append(arg)

os.execvp(args[0], args)
