#!/bin/bash
# Create simple cd catalog in few gziped text files.
# args: no arguments for find cdrom or <name> <path>

#shopt -s -o xtrace
set -o nounset
set -o errexit

if [[ ${1:-} == "-h" ]]; then
	cat <<EOF
mk_cd_catalog
- 1 parametr nazwa
- 2 ścieżka
brakujące parametry - automagiczne znalezienie
EOF
	exit 0
fi

SCRIPT=$(dirname $(readlink -f "$0"))
THIS=$(pwd)

function echotime () {
	echo "$(date +%Y-%m-%d\ %H:%M:%S): $*" > /dev/stderr
}

function findCd() {
#	mount -t iso9660,udf \
#		| awk '{ print $3; }'
	awk '/ (udf|iso9660) /{print $2}' /etc/mtab
}

if [ $# = 0 ]; then
	CD=$(findCd)
	NAME=$(basename "$CD")
else
	NAME=$1
	if [ $# = 1 ]; then
		CD=$(findCd)
	else
		CD=$2
	fi
fi

if [[ $CD == "" ]]; then
	echo "NO CD FOUND!"
	exit -1
fi

echotime "================== Start =================="
echotime "path: $CD"
echotime "name: $NAME"

echotime 'find files'
tree -psugfi "$CD" | sed "s#  ${CD}#  #" \
	| gzip > "$THIS/$NAME.files.gz"

echotime 'tree'
(
	tree -d "$CD"
	echo '--------------------'
	echo -n
	df -h "$CD"
	(cd "$CD" && du -hs .)
) | gzip > "$THIS/$NAME.tree.gz"


echotime 'readme'
if [ -e "$CD/*README*" ]; then
	cat "$CD/*README*" | gzip > "$THIS/$NAME.readme.gz"
fi

echotime 'file_id.diz'
if [ -e "$CD/file_id.diz" ]; then
	gzip -c "$CD/file_id.diz" > "$THIS/$NAME.file_id_diz.gz"
fi

echotime '*sum.txt'
(
	cd "$CD"
	find -L . -type f \( -name "md5sum.txt" -o -name "sha*sum.txt" \) -print0 \
		| tar -czf "$THIS/$NAME.sums.tar.gz" --null -T -
)

echotime 'arch'
(
	echotime '    tgz'
	find -L "$CD" \( -name "*.tgz" -o -name "*.tbz2" -o -name '*.tar.*' \) \
		-not -name "*.log" \
		-exec echo -e "\\n\\nARCHIVE {}" ';' \
		-exec tar tf "{}" ';'
	echotime '    zip'
	find -L "$CD" -name "*.zip" \
		-exec echo "\\n\\nARCHIVE {}" ';' \
		-exec bash -c '/usr/bin/unzip -l "{}" 2>&1 ;true' ';'
	echotime '    rar'
	find -L "$CD" -name "*.rar" \
		-exec echo "\\n\\nARCHIVE {}" ';' \
		-exec rar l "{}" ';'
	echotime '    7z'
	find -L "$CD" \( -name "*.7z" -o -name '*.7z.001' \) \
		-exec echo "\\n\\nARCHIVE {}" ';' \
		-exec 7z l "{}" ';'
	echotime '    xz'
	find -L "$CD" -name "*.xz" \
		-exec echo "\\n\\nARCHIVE {}" ';' \
		-exec xz -l "{}" ';'
) | gzip >  "$THIS/$NAME.arch.gz"


echotime '================= done ==================='
