#!/bin/bash -x
# Download webpage & convert to epub

set -o nounset
set -o errexit

if [[ $# == 0 ]]; then
	echo "missing args"
	exit 1
fi

URL="$1"
# find filename
HOSTPATH=${URL#*//}  # strip http[s]://
HOSTPATH=${HOSTPATH#*/}

CURRDIR=$(pwd)
TEMPDIR=$(mktemp -d)

trap "rm -rf -f -- '$TEMPDIR'" EXIT

#TEMPDIR="/tmp/tmp.eGSYzmxRt9/"

(
	cd "$TEMPDIR"
	wget -k -p -E -H -K -l 1 --reject '*.js' \
		--reject '*.eot*' --reject '*.ttf' --reject '*.woff*' \
		-t 2 \
		--user-agent='Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0' \
		-np -nH "$1"
) || true

if [[ -f "${TEMPDIR}/${HOSTPATH}" ]]; then
	FNAME="${TEMPDIR}/${HOSTPATH}"
else
	FNAME=$(ls ${TEMPDIR}/${HOSTPATH}/*.htm? | head -1)
fi

TITLE=$(pup title text{} <"$FNAME" | \
	tr -dc '[A-Za-z0-9,.-_=+()! ]' | \
	sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/[[:space:]]{2,}/ /g')
TITLE="${TITLE:-$FNAME}"

echo "TITLE: $TITLE"

STITLE=$(echo "$TITLE" | tr '[[:cntrl:]<>:"\\|?*]' '_')
OUT="$CURRDIR/$(basename "$STITLE").epub"

echo "IN: $FNAME"
echo "OUT: $OUT"

(
	cd $(dirname "$FNAME")
	pandoc -t epub3+smart --webtex --epub-chapter-level=1 -o "$OUT" "$FNAME"
)
